### ISSUE TITLE
Padding on index

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#1]
Can we reduce the padding-top so the call-to-action buttons aren't cut off on a 13" screen
<img width="806" alt="screenshot 2018-01-29 17 32 13" src="https://user-images.githubusercontent.com/1596838/35538093-a975f14a-051a-11e8-918b-5f3deab838bb.png">

**Comment by JessePeplinski** [comment]
Removed ~100px of padding. Let me know what you think & close

**Comment by dougiebuckets** [comment]
Looks good.
