### ISSUE TITLE
404s for old hack upstate's

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#10]
I get 404s for for old Hack Upstate pages. I.e., X, IX, VIII, VII. We don't have to update their formatting to match, but people still reference them. It gives more credibility to what we've done.

https://hackupstate.github.io/hackupstate-website-new/x/index.html
https://hackupstate.github.io/hackupstate-website-new/ix/index.html
https://hackupstate.github.io/hackupstate-website-new/viii/index.html
https://hackupstate.github.io/hackupstate-website-new/vii/index.html

**Comment by JessePeplinski** [comment]
On my list of todos! WIll get to this soon.

**Comment by JessePeplinski** [comment]
Uploaded all pages
