### ISSUE TITLE
Media query to resize the "Sign Up For Hack Upstate XI" CTA

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#11]
Can we add a media query to resize the "Sign Up For Hack Upstate XI" CTA for mobile?
![img-0457](https://user-images.githubusercontent.com/1596838/35593840-2d4b630a-05df-11e8-9aa8-82ecada2c7de.JPG)

**Comment by JessePeplinski** [comment]
Done
