### ISSUE TITLE
Let's reduce the width of the form fields for sponsor sign ups

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#7]
Let's reduce the width of the form fields for sponsor sign ups by 50% or so
<img width="1188" alt="screenshot 2018-01-29 17 45 42" src="https://user-images.githubusercontent.com/1596838/35538568-6575f13c-051c-11e8-9a43-c5eeac744bcf.png">

**Comment by JessePeplinski** [comment]
![done](https://user-images.githubusercontent.com/5608274/35539724-ccd4e884-0520-11e8-9eda-1b32fae46447.PNG)

Done :)
