### ISSUE TITLE
Fix picture of Jon Parry as judge

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#8]
Dimensions are messing w/ the image similar to Rachel Haot's and Jim Jurista's.
<img width="325" alt="screenshot 2018-01-29 17 48 27" src="https://user-images.githubusercontent.com/1596838/35538660-b68628d0-051c-11e8-884f-e3ba1ccf45ca.png">

**Comment by JessePeplinski** [comment]
Higher quality image added. Mind taking a look then closing?
