### ISSUE TITLE
Lunch @ 2pm instead of 3pm

### ISSUE THREAD

**Issue by dougiebuckets** [hackupstate/hackupstate-website-new#9]
Cool if we change lunch to 2pm?
<img width="547" alt="screenshot 2018-01-29 17 50 02" src="https://user-images.githubusercontent.com/1596838/35538740-e6cebb7e-051c-11e8-8474-e120a783ffbd.png">

**Comment by JessePeplinski** [comment]
Ooops, thought it was 3 :) fixed.
